### ISSUE TITLE
Java error about FilenameUtils when create .genome file

### ISSUE THREAD

**Issue by Hoxus** [igvteam/igv#453]
Hi,

For information, I work with IGV 2.3.68, java 1.8 on Ubuntu linux.

I work on a project using v6.16 release of Drosophila melanogaster genome (from Flybase).
For visualization with IGV, I tried to create my own genome file.

I have both a fasta file and a gene file.
Each time I launched the genome file creation process (after clicking ok in the box asking for the name and location of your genome file), I can read in terminal:

```
ERROR [2017-08-22 10:59:55,439]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NoClassDefFoundError: org/apache/commons/io/FilenameUtils
	at org.broad.igv.util.FileUtils.getRelativePath(FileUtils.java:118)
	at org.broad.igv.util.FileUtils.getRelativePath(FileUtils.java:196)
	at org.broad.igv.feature.genome.GenomeImporter.createGenomeArchive(GenomeImporter.java:146)
	at org.broad.igv.feature.genome.GenomeManager.defineGenome(GenomeManager.java:1240)
	at org.broad.igv.ui.IGV.doDefineGenome(IGV.java:508)
	at org.broad.igv.ui.IGVMenuBar$13.actionPerformed(IGVMenuBar.java:585)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FilenameUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more

```

After spending few time in testing, I understood I need `commons-io.jar`. I already have it, so I looked for in igv launching file in /usr/bin.
I added `:/usr/share/java/commons-io.jar` at the end of `-cp` line, and it works.

Maybe this class is lacking in the `-cp` line ?

++
Alexandre

**Comment by jrobinso** [comment]
Did you use our igv.jar file,  or build your own?    All necessary jars and
classes are included in the distributed igv.jar files.

**Comment by Hoxus** [comment]
I use the version installed by apt-get, following these informations:
http://software.broadinstitute.org/software/igv/node/152

I read this package come from multiverse repository.
For launching IGV, this kind of installation place a little shell script called IGV in /usr/bin.

I'm sorry, I didn't remember I installed with apt-get. It's not the common way.
However, I don't change anything else.

**Comment by jrobinso** [comment]
I don't know anything about apt-get,  where it comes from or who maintains
it,  so I can't help with that.   If you use our distribution you should
not have this problem.  Otherwise you can probably fix it by including the
jars in your classpath.
